[tool.poetry]
name = "myapp"
version = "0.1.0"
description = "A simple Flask application"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
flask = "^2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"